### ISSUE TITLE
Error when looking at a Assorted Decor block

### ISSUE THREAD

**Issue by evertn** [grim3212/AssortedDecor#10]
Minecraft Version: 1.16.5
Forge version: 36.2.29
Assorted Decor version: 1.16.5-2.0.14
Crash reports: The game is not crashing, so no crash log is generated.

### Error
I can only see a part of the error which is shown on screen:
ERROR: TranslatableComponent(key='block.assorteddecor.colorizer_slop...

Also, when this error occurs, everything in the hotbar disappears, that is, the images of what I have in my hotbar disappear. I can still select what's in the hotbar, and use/place it. Whenever I open my inventory, the images return.

Also, the player model disappears, I cant see whats in my hand and when you switch to 3rd-person camera, the model is just gone. This I cannot fix by opening the inventory.

Lastly, whenever its raining, I cant see the rain.

### Screenshot
[Screenshot](https://i.imgur.com/PNrWFO3.png)

On the screenshot you can see:
- The error.
- Every image on the hotbar is gone.
- Whatever I have in my hand is not visible.

If you need anything else from me, please let me know. For example, where I can find the complete error.

**Comment by grim3212** [comment]
Closing since I no longer support 1.16.5
