### ISSUE TITLE
Server crashing on Startup

### ISSUE THREAD

**Issue by JuniorWolfgamingDE** [grim3212/AssortedDecor#11]
Minecraft Version: 1.19.2
Forge version: 43.2.0
Assorted Decor version: 1.19.2-6.1.3 and upwards
Crash reports: https://pastebin.com/iydpS89z

Server Crashes when loading Assorted Decor on version 6.1.3 and upwards cause of `java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists`

When downgrading to versions under 6.1.3 it works perfectly fine.

**Comment by grim3212** [comment]
Thanks for the report. I have removed all usages of that so it should be fixed in the version I just released.


assorteddecor-1.19.2-6.1.6
