### ISSUE TITLE
Crash when I put an item from assorted decor from the creative tab to my inventory

### ISSUE THREAD

**Issue by Blugori** [grim3212/AssortedDecor#2]
Hi ! My world crashed when I tried to test the mod by taking an item from assorteddecor from the creative tab and putting it in my inventory
This might have big chances to be an incompatibility with an other mod, just let me know if you can't tell where does the problem come from with the logs, and I'll try to found the culprit mod.

Minecraft : 1.16.4
Forge : 35.0.7
Assorted Decor : 2.0.2

[crash-2020-11-15_17.26.46-client.txt](https://github.com/grim3212/AssortedDecor/files/5542728/crash-2020-11-15_17.26.46-client.txt)
[debug.log](https://github.com/grim3212/AssortedDecor/files/5542729/debug.log)
[latest.log](https://github.com/grim3212/AssortedDecor/files/5542732/latest.log)

Best regards !

**Comment by grim3212** [comment]
Interesting looks to be an issue with Apotheosis. Let me see if I can figure out why. Might be a quick change on my part but I don't know for sure.

**Comment by grim3212** [comment]
I was able to reproduce it with just Apotheosis and Assorted Decor, thought mine didn't crash. Let me see what I can figure out.

`[06:34:48] [Render thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Client
java.lang.NullPointerException: null
	at com.grim3212.assorted.decor.common.block.colorizer.ColorizerTableBlock.func_196258_a(ColorizerTableBlock.java:76) ~[assorteddecor:1.16.4-2.0.2] {re:classloading}
	at shadows.apotheosis.ench.EnchModuleClient.tooltips(EnchModuleClient.java:44) ~[apotheosis:4.4.1] {re:classloading}`

**Comment by Blugori** [comment]
thanks ! good luck :)

**Comment by grim3212** [comment]
Alright a new version should be up shortly that _should_ fix this. I was no longer seeing it occur when running the two together.
