### ISSUE TITLE
[Request] Vertical Slab Block

### ISSUE THREAD

**Issue by Xaikii** [grim3212/AssortedDecor#3]
Title says it all ^^'

I tried all currently avaible Blocks, and it's not possible to use any of the Blocks as a Vertical Slab(like in Quark).

**Comment by grim3212** [comment]
That makes sense as something to add. I have never used the vertical slab before. Is it still able to combine into two blocks?

**Comment by Xaikii** [comment]
Yes it can be combined, 2 Vertical Slabs form a Full Block

**Comment by grim3212** [comment]
Alright cool when I get some time I should be able to get that added as the next addition to Decor.

**Comment by grim3212** [comment]
Added in the latest release of Assorted Decor.
