### ISSUE TITLE
Crash on Server when placing colorizer block

### ISSUE THREAD

**Issue by judicius** [grim3212/AssortedDecor#6]
MC 1.16.5
Forge 36.1.13
Assorted Decor 2.0.10

**https://gist.github.com/judicius/2f110af96e349873166045eb6dd12903**

Player placed a colorizer block and was disconnected with "not closed container" error. 
New player went to destroy colorizer block  and was DC'd as well.

Issue doesn't seem to happen in an SP world just on a server.

**Comment by grim3212** [comment]
Do you happen to know of any other mods that may be conflicting?
I am unable to reproduce this with just Assorted Decor.

**Comment by judicius** [comment]
Just updated the pack with a bunch of mod updates as well and now there is no problem so i'm going to close this and hope it's all good.
