### ISSUE TITLE
Colorizer Table and Stool Blocks Cause Server Crash with Illegal Argument Exception when Interacting with TNT Explosions

### ISSUE THREAD

**Issue by connorlaw2151** [grim3212/AssortedDecor#7]
![image](https://user-images.githubusercontent.com/46633262/126873661-5a54f6c1-6a19-4da6-8846-e351ac211044.png)
# Requested Information
Forge 36.2.0  
Minecraft 1.16.5  
Assorted Decor 2.0.13  
# Current Behavior
When a block of TNT explodes and one of
+ Colorizer Table
+ Colorizer Stool

are in within the blast radius, the server will crash immediately with `java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=up, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}` as the primary error. For stack trace, see pastebins. As such the side effects are severe resulting in data loss since the last save point, etc. This issue should be categorized as severe.

Primary Crash Report: https://pastebin.com/KK4iJTub

All Other Crash Reports from Testing (basically the same content)
+ https://pastebin.com/BCTGk2qx
+ https://pastebin.com/1wuTR7gg
+ https://pastebin.com/NG4G7u3G
+ https://pastebin.com/jj9g6VLz

# Expected Behavior
Server should not crash

# Steps to Reproduce
1. Place either of the above blocks
2. Place a block of TNT, or a chain of TNT
3. Cause the TNT to explode in any manner.

# Detailed Description
The issue was first noticed a few weeks ago during an event on a server I administrate. The plan was to explode a series of buildings in a town on the server as part of the finale for the server's season (as it is a content server.) Immediately upon exploding the first block of TNT, the server crashed. At first my suspicion was it linked to the large TNT explosion This continued repeatedly (sometimes crashing on first player join until I reset the world's data folder. I used WorldEdit to remove all the TNT that had previously been placed. Even so, the crash would still occur when the conditions above were met.

As I was testing mods to be able to update the server, I experimented with TNT. The TNT performed normally in a generated world, so I imported a copy of the world with all the TNT in it, and again experienced the crash, even with the current recommended version of Forge (36.2.0 - 1.16.5). The crash does not occur in unmodded forge, or with any other mods installed. I tested all Colorizer blocks, and it only occurs with these two. It occurs every time consistently.

**Comment by grim3212** [comment]
Thanks for the report. I am pretty sure I have found the issue. After some more testing I will update here.

**Comment by grim3212** [comment]
Again thanks for the super detailed bug report. It should be fixed in the latest version for 1.16.5 https://www.curseforge.com/minecraft/mc-mods/assorted-decor/files/3402377 as well as going forward for any updates in 1.17.
