### ISSUE TITLE
Cactus can't be planted on sandy planter pot

### ISSUE THREAD

**Issue by WenXin20** [grim3212/AssortedDecor#8]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Assorted Decor v2.0.14`

I noticed that cactus can't be planted on the Planter Pot even when it is set to use sand as the soil.

**Comment by grim3212** [comment]
Not sure how I missed a notification of this bug. But this was indeed a problem. I have fixed it with the latest 1.18 update. I can probably backport the fix to 1.16 just let me know if it is still needed.

**Comment by WenXin20** [comment]
No worries! 1.18 is fine, I've moved to that update too. :)

**Comment by grim3212** [comment]
Awesome! Sounds good.
